TYPE=VIEW
query=select `reg`.`id_registro` AS `id_registro`,`reg`.`id_servicio` AS `id_servicio`,`reg`.`id_distrito` AS `id_distrito`,`reg`.`id_circuito` AS `id_circuito`,`reg`.`id_iglesia` AS `id_iglesia`,`reg`.`id_persona` AS `id_persona`,`reg`.`es_miembro_iglesia` AS `es_miembro_iglesia`,`reg`.`es_lider` AS `es_lider`,`reg`.`es_miembro_ministerial` AS `es_miembro_ministerial`,`reg`.`es_pastor` AS `es_pastor`,`reg`.`es_presbitero` AS `es_presbitero`,`reg`.`es_delegado` AS `es_delegado`,`reg`.`es_visita` AS `es_visita`,`reg`.`es_miembro_comite_temp` AS `es_miembro_comite_temp`,`reg`.`es_exonerado` AS `es_exonerado`,`reg`.`fecha_registro` AS `fecha_registro`,`reg`.`hora_registro` AS `hora_registro`,`p`.`nombres` AS `nombres`,`p`.`apellidos` AS `apellidos`,`cir`.`circuito` AS `circuito`,`d`.`distrito` AS `distrito`,`i`.`iglesia` AS `iglesia`,`rango`.`rango_ministerial` AS `rango_ministerial`,`soc`.`sociedad` AS `sociedad` from (((((((`iglesias`.`registro` `reg` join `iglesias`.`circuitos` `cir` on((`reg`.`id_circuito` = `cir`.`id_circuito`))) join `iglesias`.`iglesias` `i` on((`reg`.`id_iglesia` = `i`.`id_iglesia`))) join `iglesias`.`personas` `p` on((`reg`.`id_persona` = `p`.`id_persona`))) join `iglesias`.`distritos` `d` on((`reg`.`id_distrito` = `d`.`id_distrito`))) join `iglesias`.`miembros` `m` on((`p`.`id_persona` = `m`.`id_persona`))) join `iglesias`.`sociedades` `soc` on((`m`.`id_sociedad` = `soc`.`id_sociedad`))) join `iglesias`.`rango_ministerial` `rango` on((`m`.`id_rango_ministerial` = `rango`.`id_rango`)))
md5=40e06ebb1b7c66b2ffbd8bc941079d1a
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2019-05-22 18:44:02
create-version=1
source=SELECT reg.* \n, p.nombres\n, p.apellidos\n, cir.circuito\n, d.distrito\n, i.iglesia\n, rango.rango_ministerial\n, soc.sociedad\n\nFROM registro reg \n inner join circuitos cir on reg.id_circuito=cir.id_circuito\ninner join iglesias i on reg.id_iglesia=i.id_iglesia\ninner join personas p on reg.id_persona=p.id_persona\ninner join distritos d on reg.id_distrito=d.id_distrito\ninner join miembros m on p.id_persona = m.id_persona\ninner join sociedades soc on m.id_sociedad = soc.id_sociedad\ninner join rango_ministerial rango on m.id_rango_ministerial = rango.id_rango
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `reg`.`id_registro` AS `id_registro`,`reg`.`id_servicio` AS `id_servicio`,`reg`.`id_distrito` AS `id_distrito`,`reg`.`id_circuito` AS `id_circuito`,`reg`.`id_iglesia` AS `id_iglesia`,`reg`.`id_persona` AS `id_persona`,`reg`.`es_miembro_iglesia` AS `es_miembro_iglesia`,`reg`.`es_lider` AS `es_lider`,`reg`.`es_miembro_ministerial` AS `es_miembro_ministerial`,`reg`.`es_pastor` AS `es_pastor`,`reg`.`es_presbitero` AS `es_presbitero`,`reg`.`es_delegado` AS `es_delegado`,`reg`.`es_visita` AS `es_visita`,`reg`.`es_miembro_comite_temp` AS `es_miembro_comite_temp`,`reg`.`es_exonerado` AS `es_exonerado`,`reg`.`fecha_registro` AS `fecha_registro`,`reg`.`hora_registro` AS `hora_registro`,`p`.`nombres` AS `nombres`,`p`.`apellidos` AS `apellidos`,`cir`.`circuito` AS `circuito`,`d`.`distrito` AS `distrito`,`i`.`iglesia` AS `iglesia`,`rango`.`rango_ministerial` AS `rango_ministerial`,`soc`.`sociedad` AS `sociedad` from (((((((`iglesias`.`registro` `reg` join `iglesias`.`circuitos` `cir` on((`reg`.`id_circuito` = `cir`.`id_circuito`))) join `iglesias`.`iglesias` `i` on((`reg`.`id_iglesia` = `i`.`id_iglesia`))) join `iglesias`.`personas` `p` on((`reg`.`id_persona` = `p`.`id_persona`))) join `iglesias`.`distritos` `d` on((`reg`.`id_distrito` = `d`.`id_distrito`))) join `iglesias`.`miembros` `m` on((`p`.`id_persona` = `m`.`id_persona`))) join `iglesias`.`sociedades` `soc` on((`m`.`id_sociedad` = `soc`.`id_sociedad`))) join `iglesias`.`rango_ministerial` `rango` on((`m`.`id_rango_ministerial` = `rango`.`id_rango`)))
